# Generated by Django 2.1.1 on 2019-07-25 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_address', models.ImageField(upload_to='store/images', verbose_name='图片地址')),
                ('img_description', models.TextField(max_length=32, verbose_name='图片描述')),
            ],
        ),
        migrations.RemoveField(
            model_name='goodsiimg',
            name='goods_id',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_under',
            field=models.IntegerField(default=1, verbose_name='商品状态'),
        ),
        migrations.DeleteModel(
            name='GoodsiImg',
        ),
        migrations.AddField(
            model_name='goodsimg',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Goods', verbose_name='商品id'),
        ),
    ]
