# Generated by Django 2.1.1 on 2019-07-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20190725_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_number',
            field=models.IntegerField(verbose_name='商品数量库存'),
        ),
    ]
