# Generated by Django 2.1.1 on 2019-07-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20190725_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods_under',
            new_name='goods_state',
        ),
    ]
